### ISSUE TITLE
mips OpenWRT无法运行

### ISSUE THREAD

**Issue by WeiqiChenCN** [esrrhs/pingtunnel#41]
运行情况如下所示：
```
root@Netgear-OpenWrt:~# ./pingtunnel
./pingtunnel: line 1: syntax error: unexpected "("
root@Netgear-OpenWrt:~# uname -a
Linux Netgear-OpenWrt 4.14.180 #0 SMP Sat May 16 18:32:20 2020 mips GNU/Linux
root@Netgear-OpenWrt:~#
```
版本：
OpenWrt 19.07.3

**Comment by esrrhs** [comment]
![图片](https://user-images.githubusercontent.com/4083816/91967513-ecd30480-ed45-11ea-8829-91b948a01eaa.png)
试试release里的这俩呢？

**Comment by WeiqiChenCN** [comment]
```
scp pingtunnel netgear-openwrt:/root/pingtunnel_mips
scp pingtunnel netgear-openwrt:/root/pingtunnel_mipsle
ssh netgear-openwrt
root@Netgear-OpenWrt:~# ./pingtunnel_mips
./pingtunnel_mips: line 1: syntax error: unexpected "("
root@Netgear-OpenWrt:~# ./pingtunnel_mipsle
Illegal instruction
```
不行，如上。

**Comment by esrrhs** [comment]
cat /proc/cpuinfo 看看

**Comment by WeiqiChenCN** [comment]
```
root@Netgear-OpenWrt:~# cat /proc/cpuinfo
system type             : MediaTek MT7621 ver:1 eco:3
machine                 : Netgear R6220
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 584.90
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_dcache userlocal vint perf_cntr_intr_bit cdmm nan_legacy nan_2008 perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 584.90
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_dcache userlocal vint perf_cntr_intr_bit cdmm nan_legacy nan_2008 perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by esrrhs** [comment]
![图片](https://user-images.githubusercontent.com/4083816/92085649-b22ba380-edfb-11ea-8b18-9952f10f549c.png)
试试这几个？还不行就真不行了吧

**Comment by WeiqiChenCN** [comment]
根据[golang binary not running on mips](https://stackoverflow.com/questions/55154143/golang-binary-not-running-on-mips)我欲尝试自己编译试一试，但是遇到了如下问题：

```
~/pingtunnel$ GOOS=linux GOARCH=mips go build
main.go:6:2: cannot find package "github.com/esrrhs/go-engine/src/common" in any of:
        /usr/lib/go-1.13/src/github.com/esrrhs/go-engine/src/common (from $GOROOT)
        /home/weiqi/go/src/github.com/esrrhs/go-engine/src/common (from $GOPATH)
main.go:7:2: cannot find package "github.com/esrrhs/go-engine/src/geoip" in any of:
        /usr/lib/go-1.13/src/github.com/esrrhs/go-engine/src/geoip (from $GOROOT)
        /home/weiqi/go/src/github.com/esrrhs/go-engine/src/geoip (from $GOPATH)
main.go:8:2: cannot find package "github.com/esrrhs/go-engine/src/loggo" in any of:
        /usr/lib/go-1.13/src/github.com/esrrhs/go-engine/src/loggo (from $GOROOT)
        /home/weiqi/go/src/github.com/esrrhs/go-engine/src/loggo (from $GOPATH)
main.go:9:2: cannot find package "github.com/esrrhs/go-engine/src/pingtunnel" in any of:
        /usr/lib/go-1.13/src/github.com/esrrhs/go-engine/src/pingtunnel (from $GOROOT)
        /home/weiqi/go/src/github.com/esrrhs/go-engine/src/pingtunnel (from $GOPATH)
```

其实我想添加一个参数试一试：`GOOS=linux GOARCH=mips GOMIPS=softfloat go build`

**Comment by esrrhs** [comment]
如果你网速快的话，可以试试 go get -v github.com/esrrhs/go-engine/...
我帮你build一个试试

[pingtunnel.zip](https://github.com/esrrhs/pingtunnel/files/5167732/pingtunnel.zip)

**Comment by WeiqiChenCN** [comment]
` GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build` 可以了。

**Comment by WeiqiChenCN** [comment]
好不容易可以运行了，结果会崩溃退出。
```
[0;00m[38;5;46m[INFO] [2020-09-03T11:18:16.455624374Z] [client.go:332] [github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcpConn] client accept new local tcp f2820856621708be32875c0153d51b67 127.0.0.1:42096
[0;00m[38;5;46m[INFO] [2020-09-03T11:18:16.456116272Z] [client.go:334] [github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcpConn] start connect remote tcp f2820856621708be32875c0153d51b67 127.0.0.1:42096
[0;00m[38;5;46m[INFO] [2020-09-03T11:18:16.508347245Z] [client.go:365] [github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcpConn] connected remote tcp c450657b087d7fb10c1473dbf315c189 127.0.0.1:42086
[0;00m[38;5;46m[INFO] [2020-09-03T11:18:16.510316386Z] [client.go:365] [github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcpConn] connected remote tcp b6193ce6f68291b950ec0f6e12318e23 127.0.0.1:42092
[0;00m[38;5;46m[INFO] [2020-09-03T11:18:16.511085446Z] [client.go:365] [github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcpConn] connected remote tcp f2820856621708be32875c0153d51b67 127.0.0.1:42096
[0;00m[38;5;46m[INFO] [2020-09-03T11:18:16.513641269Z] [client.go:365] [github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcpConn] connected remote tcp d96e3bb805ef310328b4de78441ee072 127.0.0.1:42084
[0;00mfatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5da816, 0x16)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x60
runtime.sysMap(0x3c00000, 0x400000, 0x9b7ed8)
	/usr/lib/go-1.13/src/runtime/mem_linux.go:169 +0xec
runtime.(*linearAlloc).alloc(0x9ac098, 0x400000, 0x400000, 0x9b7ed8, 0x10827fc)
	/usr/lib/go-1.13/src/runtime/malloc.go:1387 +0xd0
runtime.(*mheap).sysAlloc(0x9abda0, 0x100000, 0x3d870, 0x0)
	/usr/lib/go-1.13/src/runtime/malloc.go:607 +0x7c
runtime.(*mheap).grow(0x9abda0, 0x80, 0xffffffff)
	/usr/lib/go-1.13/src/runtime/mheap.go:1255 +0xbc
runtime.(*mheap).allocSpanLocked(0x9abda0, 0x80, 0x9b7ee8, 0x0)
	/usr/lib/go-1.13/src/runtime/mheap.go:1170 +0x2d0
runtime.(*mheap).alloc_m(0x9abda0, 0x80, 0x101, 0x0)
	/usr/lib/go-1.13/src/runtime/mheap.go:1022 +0xfc
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.13/src/runtime/mheap.go:1093 +0x5c
runtime.(*mheap).alloc(0x9abda0, 0x80, 0x1010101, 0x272e1c0)
	/usr/lib/go-1.13/src/runtime/mheap.go:1092 +0x90
runtime.largeAlloc(0x100000, 0x101, 0x1001500)
	/usr/lib/go-1.13/src/runtime/malloc.go:1138 +0xa0
runtime.mallocgc.func1()
	/usr/lib/go-1.13/src/runtime/malloc.go:1033 +0x58
runtime.systemstack(0x0)
	/usr/lib/go-1.13/src/runtime/asm_mipsx.s:207 +0x9c
runtime.mstart()
	/usr/lib/go-1.13/src/runtime/proc.go:1146

goroutine 31 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.13/src/runtime/asm_mipsx.s:159 +0x8 fp=0x3a7d378 sp=0x3a7d374 pc=0x8043c
runtime.mallocgc(0x100000, 0x54e2c0, 0x1, 0x2319a70)
	/usr/lib/go-1.13/src/runtime/malloc.go:1032 +0x9f8 fp=0x3a7d3cc sp=0x3a7d378 pc=0x1d1a0
runtime.makeslice(0x54e2c0, 0x100000, 0x100000, 0x1019810)
	/usr/lib/go-1.13/src/runtime/slice.go:49 +0xa0 fp=0x3a7d3e0 sp=0x3a7d3cc pc=0x646d4
github.com/esrrhs/go-engine/src/rbuffergo.New(...)
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/rbuffergo/rbuffergo.go:45
github.com/esrrhs/go-engine/src/frame.NewFrameMgr(0x378, 0xf4240, 0x100000, 0x4e20, 0x190, 0x0, 0x0, 0x0)
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/frame/framemgr.go:100 +0x6c fp=0x3a7d4ec sp=0x3a7d3e0 pc=0x2f6d20
github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcpConn(0x1084600, 0x2381128, 0x7fb96e7a, 0x13)
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/pingtunnel/client.go:326 +0x174 fp=0x3a7ffdc sp=0x3a7d4ec pc=0x325440
runtime.goexit()
	/usr/lib/go-1.13/src/runtime/asm_mipsx.s:657 +0x4 fp=0x3a7ffdc sp=0x3a7ffdc pc=0x827d4
created by github.com/esrrhs/go-engine/src/pingtunnel.(*Client).AcceptTcp
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/pingtunnel/client.go:303 +0x264

goroutine 1 [sleep]:
runtime.goparkunlock(...)
	/usr/lib/go-1.13/src/runtime/proc.go:310
time.Sleep(0x30b8a000, 0x346)
	/usr/lib/go-1.13/src/runtime/time.go:105 +0x1a0
main.main()
	/home/weiqi/pingtunnel/main.go:267 +0x104c

goroutine 6 [sleep]:
runtime.goparkunlock(...)
	/usr/lib/go-1.13/src/runtime/proc.go:310
time.Sleep(0x3b9aca00, 0x0)
	/usr/lib/go-1.13/src/runtime/time.go:105 +0x1a0
github.com/esrrhs/go-engine/src/common.updateNowInSecond()
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/common/time.go:23 +0x74
created by github.com/esrrhs/go-engine/src/common.init.1
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/common/time.go:11 +0x88

goroutine 18 [sleep]:
runtime.goparkunlock(...)
	/usr/lib/go-1.13/src/runtime/proc.go:310
time.Sleep(0x30b8a000, 0x346)
	/usr/lib/go-1.13/src/runtime/time.go:105 +0x1a0
github.com/esrrhs/go-engine/src/loggo.loopCheck(0x1, 0x5d3950, 0xa, 0x3, 0x1)
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/loggo/loggo.go:340 +0xa0
created by github.com/esrrhs/go-engine/src/loggo.Ini
	/home/weiqi/go/src/github.com/esrrhs/go-engine/src/loggo/loggo.go:61 +0x160

```
```
root@Netgear-OpenWrt:~# free -h
              total        used        free      shared  buff/cache   available
Mem:         123880       86984       20820        2024       16076        4340
Swap:             0           0           0
```

**Comment by WeiqiChenCN** [comment]
哈哈，我在树莓派上跑，CPU占用100%+，16%内存。恐怕是无法在我的路由器上跑了。

**Comment by esrrhs** [comment]
调小窗口和buffer的话，应该可以的。默认参数在我的newifi新路由3是可以跑起来的
